export interface IWeather {
    time: number,
    timeString: string,
    summary: string,
    icon: string,
    precipIntensity: number,
    precipProbability: number,
    precipType: string,
    temperature: number,
    apparentTemperature: number,
    dewPoint: number,
    humidity:number,
    pressure: number,
    windSpeed: number,
    windGust: number,
    windBearing: number,
    windBearingDescription: string,
    cloudCover: number,
    uvIndex: number,
    uvIndexDescription: string,
    visibility: number,
    ozone: number,
    nearestStormBearing: number,
    nearestStormDistance: number
}